import React from 'react'
import Navbar from '../components/Navbar'
import SideNav from '../components/SideNav'

const Home = () => {
  return (
    <div className='font-serif'>
        <Navbar/>
        <div className='flex'>
        <SideNav/>
        <div className='mx-auto text-center ps-50'>
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            edrftgyhujikol;edrtfgyuhjkash8uijkweashduijknm
            
        </div>
        </div>
        
    </div>
  )
}

export default Home